# LangChain4J for OpenAI model configuration
quarkus.langchain4j.openai.base-url=${OVH_AI_ENDPOINTS_MODEL_URL}
quarkus.langchain4j.openai.chat-model.model-name=${OVH_AI_ENDPOINTS_MODEL_NAME}
quarkus.langchain4j.openai.api-key=${OVH_AI_ENDPOINTS_ACCESS_TOKEN}
quarkus.langchain4j.openai.embedding-model.model-name=${OVH_AI_ENDPOINTS_EMBEDDING_MODEL_NAME}
quarkus.langchain4j.openai.chat-model.temperature=0
quarkus.langchain4j.openai.timeout=3600
quarkus.langchain4j.openai.log-requests=false
quarkus.langchain4j.openai.log-responses=false

## AI Endpoints parameters
ovhcloud.ai-endpoints.token=${OVH_AI_ENDPOINTS_ACCESS_TOKEN}